core/core-test/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/core/test/test_setup/course_creation/CourseManagementRequests.kt, feature/quiz/src/test/kotlin/de/tum/informatics/www1/artemis/native_app/feature/quiz/QuizBaseE2eTest.kt, feature/quiz/src/test/kotlin/de/tum/informatics/www1/artemis/native_app/feature/quiz/QuizParticipationBaseE2eTest.kt, feature/quiz/src/test/kotlin/de/tum/informatics/www1/artemis/native_app/feature/quiz/QuizWaitingScreenE2eTest.kt
Recently, the e2e tests have been broken due to a change in the drag and drop quiz image upload.
=> Chore: Fix background image file upload in quiz exercises.

feature/metis/conversation/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/metis/conversation/service/storage/impl/MetisStorageServiceImpl.kt, feature/metis/shared/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/metis/shared/db/MetisDao.kt
Fixed bug causing answers in threads to not display.
This PR solves the issue [#53](https://github.com/ls1intum/artemis-android/issues/53)
=> Fix thread answers not shown

core/ui/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/core/ui/exercise/ExerciseActionButtons.kt
As discussed in #107 we have to temporarly disable quiz participation as it is not working currently
=> Disabled quiz participation

feature/exercise-view/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/exerciseview/home/ExerciseScreen.kt, feature/exercise-view/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/exerciseview/home/ExerciseScreenBody.kt, feature/exercise-view/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/exerciseview/home/ExerciseScreenTopAppBar.kt, feature/exercise-view/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/exerciseview/home/overview/ExerciseOverviewTab.kt
There was a bug that the exercise titles where not shown, see #120 .
- Showing exercise title
- Removed the collapsible ExerciseTopAppBar
- Rearrange ExerciseInfo to ExerciseOverviewTab.kt
Phone
Tablet
Foldable
=> `Bugfix`: Show exercise title

Dockerfile, app/build.gradle.kts
Stephan made me aware that we still have running bamboo builds which were replaced with github actions for this repo, so I also searched the code for remaining (and now unused) bamboo configs.
Removed the bambo buildNumber.
=> `Chore`: Remove unused bamboo buildNumber

core/ui/src/debug/kotlin/de/tum/informatics/www1/artemis/native_app/core/ui/ScreenshotFrame.kt, core/ui/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/core/ui/exercise/ExerciseActionButtons.kt, core/ui/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/core/ui/exercise/ExerciseCategoryChips.kt, feature/exercise-view/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/exerciseview/home/overview/ExerciseOverviewTab.kt, feature/metis/conversation/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/metis/conversation/ui/post/PostContextBottomSheet.kt, feature/metis/manage-conversations/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/metis/manageconversations/ui/conversation/browse_channels/BrowseChannelsScreen.kt, feature/metis/manage-conversations/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/metis/manageconversations/ui/conversation/overview/ConversationOverviewBody.kt
See #103 
- Using `MaterialTheme.shapes.xxx` where applicable
=> `Chore`: Use material shapes

.gitignore, build-logic/convention/src/main/kotlin/AndroidApplicationComposeConventionPlugin.kt, build-logic/convention/src/main/kotlin/AndroidApplicationConventionPlugin.kt, build-logic/convention/src/main/kotlin/AndroidFeatureConventionPlugin.kt, build-logic/convention/src/main/kotlin/AndroidLibraryComposeConventionPlugin.kt, build-logic/convention/src/main/kotlin/AndroidLibraryConventionPlugin.kt, build-logic/convention/src/main/kotlin/AndroidRoomConventionPlugin.kt, build-logic/convention/src/main/kotlin/commonConfiguration/AndroidCompose.kt, build-logic/convention/src/main/kotlin/commonConfiguration/KotlinAndroid.kt, build-logic/convention/src/main/kotlin/util/ProjectExtensions.kt, build.gradle.kts, download-dependencies/app/build.gradle.kts, feature/exercise-view/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/exerciseview/home/overview/ExerciseOverviewTab.kt, gradle/libs.versions.toml
The project did not make use of the new K2 compiler yet.
This PR is part of #128.
- Updated dependencies to use kotlin 2.0
- Cleaned up version catalog and build logic
See that everything works as previously
=> `Chore`: Update project to kotlin 2.0

gradle/libs.versions.toml
Reverts ls1intum/artemis-android#281
=> Revert "Bump androidGradlePlugin from 8.7.1 to 8.8.0"

core/ui/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/core/ui/Spacings.kt, feature/course-view/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/courseview/ui/course_overview/CourseUiScreen.kt, feature/lecture-view/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/lectureview/LectureOverviewTab.kt, feature/lecture-view/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/lectureview/LectureScreenBody.kt, feature/metis/conversation/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/metis/conversation/ui/ConversationThreadScreen.kt, feature/metis/conversation/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/metis/conversation/ui/chatlist/MetisChatList.kt, feature/metis/conversation/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/metis/conversation/ui/thread/MetisThreadUi.kt, feature/metis/manage-conversations/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/metis/manageconversations/ui/conversation/browse_channels/BrowseChannelsScreen.kt, feature/metis/manage-conversations/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/metis/manageconversations/ui/conversation/create_channel/CreateChannelScreen.kt, feature/metis/manage-conversations/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/metis/manageconversations/ui/conversation/create_personal_conversation/CreatePersonalConversationScreen.kt, feature/metis/manage-conversations/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/metis/manageconversations/ui/conversation/create_personal_conversation/PotentialRecipientsUi.kt, feature/metis/manage-conversations/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/metis/manageconversations/ui/conversation/member_selection/MemberSelection.kt, feature/metis/manage-conversations/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/metis/manageconversations/ui/conversation/settings/add_members/ConversationAddMembersScreen.kt, feature/metis/manage-conversations/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/metis/manageconversations/ui/conversation/settings/members/ConversationMembersBody.kt, feature/metis/manage-conversations/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/metis/manageconversations/ui/conversation/settings/members/ConversationMembersScreen.kt
See #305 
- Removed spacing from `metisModifier` and applied to all subsequent screens consistently
Test that the spacings in the app all look consistent
=> `Chore`: Fix spacings

buildSrc/build.gradle.kts
Reverts ls1intum/artemis-android#349
=> Revert "Bump jvm from 2.1.0 to 2.1.10"

buildSrc/build.gradle.kts
Reverts ls1intum/artemis-android#347
=> Revert "Bump plugin.serialization from 2.1.0 to 2.1.10"

core/websocket/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/core/websocket/impl/WebsocketProviderImpl.kt
Often we were missing websocket heartbeats, leading to all websocket subscriptions having to re-subscribe.
This closes #393 
- Added HeartBeatTolerance
- Go to ConversationOverview
- Wait a few minutes
- See that there are no "Missing heartbeat" error logs in logcat
=> `Bugfix`: Add websocket heartbeat tolerance

feature/metis/manage-conversations/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/metis/manageconversations/ui/conversation/PotentiallyIllegalTextField.kt, feature/metis/manage-conversations/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/metis/manageconversations/ui/conversation/create_channel/CreateChannelScreen.kt, feature/metis/manage-conversations/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/metis/manageconversations/ui/conversation/settings/add_members/ConversationAddMembersScreen.kt
This is a small PR that fixes some padding issues in the communication module.
CreateChannelScreen has extra padding to the TopBar as well as AddMemberScreen.
An icon has been added to the name textfield in CreateChannelScreen
Make sure everything looks good.
=> `Bugfix`: Fix padding issues

.github/workflows/release.yml, app/build.gradle.kts, developerDocs/Release.md
Reverts ls1intum/artemis-android#512
=> Revert "`CI`: Upload app to Play Console via GitHub actions"

app/src/main/java/de/tum/informatics/www1/artemis/native_app/android/ui/RootNavGraph.kt, core/data/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/core/data/service/Api.kt, core/ui/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/core/ui/remote_images/impl/ArtemisImageProviderImpl.kt, feature/exercise-view/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/exerciseview/ExerciseViewUi.kt, feature/exercise-view/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/exerciseview/home/ExerciseScreen.kt, feature/exercise-view/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/exerciseview/home/ExerciseScreenBody.kt, feature/exercise-view/src/test/kotlin/de/tum/informatics/www1/artemis/native_app/feature/exercise_view/participate/text_exercise/ExerciseOverviewE2eTest.kt, feature/lecture-view/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/lectureview/LectureScreenUi.kt
There has been a problem loading lecture slides since the 8.0 api changes.
This PR closes #510 
- Use 8.0 API endpoint
- Removing unused code that has been bothering me since months :D 
- Go to a server with 8.0 API
- Go to a lecture with a pdf lecture unit
- Open the pdf by clicking on the lecture unit
=> `Bugfix`: Fix lecture unit pdfs loading error

core/datastore/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/core/datastore/defaults/ArtemisInstances.kt
See #523. Update the KIT artemis instance URL
=> `Chore`: Update KIT url

.whitesource
We are having issues with Mend since weeks now, some checks are randomly reported as failures, with no reasonable explanation. I already contacted Mend support, but still got not helpful answer / fix.
Changes according to https://docs.mend.io/integrations/latest/configure-mend-for-github-com-for-sca#ConfigureMendforGitHub.comforSCA-CheckRunSettings(checkRunSettings)
=> Change vulnerableCheckRunConclusionLevel to "none"

feature/dashboard/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/dashboard/service/impl/SurveyHintServiceImpl.kt
=> `Chore`: Enable survey2 for new semester

feature/lecture-view/src/test/kotlin/de/tum/informatics/www1/artemis/native_app/feature/lecture_view/LectureE2eTest.kt, feature/push/src/test/kotlin/de/tum/informatics/www1/artemis/native_app/feature/push/PushNotificationSettingsE2eTest.kt
Some E2E tests were consistently failing.
Ignore outdated tests and created issue for it
=> `Chore`: Fix failing e2e tests

feature/settings/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/settings/ui/SettingsScreen.kt, feature/settings/src/main/res/values/settings_strings.xml
The build section of the settings now includes a button linking the issue list of this repo.
=> `Improvement`: Add bug report button

feature/metis/conversation/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/metis/conversation/service/network/impl/MetisServiceImpl.kt
See #588 and #462 
This PR migrates the MetisService to use the new endpoint structure for forwarded messages. In addition, a try-catch block has been added to catch the error, that is currently thrown in the console when loading forwarded messages.
This PR fixes #588 and closes #462.
1. Make sure all functionalities related to forwarded messages work fine.
2. Make sure there is no error thrown in the console.
=> `Chore`: Adjust Endpoints and Fix Error in Console

developerDocs/10MinuteTest.md, developerDocs/Release.md
To ensure that the basic and most crucial app functionality works for every release, I created these manual test steps. 
Let me know if you have any additions or stuff that I missed :)
=> `Chore`: Add 10 minute test steps

feature/course-notifications/src/test/kotlin/de/tum/informatics/www1/artemis/native_app/feature/coursenotifications/CourseNotificationSettingsE2eTest.kt, gradle/libs.versions.toml
- Update targetSdk to 35 to conform with GooglePlay policy
- remove flaky tests
=> `Chore`: Update target sdk and fix flaky e2e test
