ls1intum/artemis-android

- app/src/main/java/de/tum/informatics/www1/artemis/native_app/android/db/AppDatabase.kt
Increase database version to prevent app crashes introduced by last hotfix (AppVersion 467, Schema update in [this commit](https://github.com/ls1intum/artemis-android/commit/5a185d515746fb7f1ccdf3bf3eedc771f1be843f))
Error in GooglePlayConsole:
`de.tum.informatics.www1.artemis.native_app.feature.metis.shared.db.MetisDao_Impl$42.call`
> Hotfix for Crash de.tum.informatics.www1.artemis.native_app.feature.metis.shared.db.MetisDao_Impl$42.call

- core/common/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/core/common/flowutil.kt
- feature/dashboard/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/dashboard/CoursesOverview.kt
- feature/metis/manage-conversations/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/metis/manageconversations/ui/conversation/create_personal_conversation/PotentialRecipientsUi.kt
- feature/metis/manage-conversations/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/metis/manageconversations/ui/conversation/member_selection/MemberSelection.kt
- feature/metis/manage-conversations/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/metis/manageconversations/ui/conversation/member_selection/MemberSelectionBaseViewModel.kt
- feature/metis/manage-conversations/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/metis/manageconversations/ui/conversation/overview/ConversationOverviewBody.kt
- feature/metis/manage-conversations/src/main/res/values/conversation_member_selection_strings.xml
- Beta Version Dialog: Press on text now also toggle checkbox
- Made CodeOfConduct button less prominent and more similar to iOS 
- CreateChat: Enhanced search texts by adding a text when the search query is too short
> Small UI Improvements

- core/data/build.gradle.kts
Removing the ktor-client-cio for debug, because it caused ConnectionTimeout Errors after the 100th request.
This closes the problem described in issue  #69. Note that this problem did not occur on the release version of the app.
I ensured that no new tests fail because of this change by running the E2E tests locally.
> Fix ConnectionTimout in debug mode

- feature/login/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/login/login/LoginViewModel.kt
- feature/login/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/login/login_module.kt
- feature/login/src/test/java/de/tum/informatics/www1/artemis/native_app/feature/login/login_moduleTest.kt
While working on another ticket, I found that the app crashes when navigating to the register screen.
I created unit tests that ensure that there are no error when initializing the ViewModels.
- If you are currently logged into the app, log out by tapping the settings / gear icon and choose "Logout"
- Press "not your university"
- Choose "TUM test-server-2"
- Press register -> previously the app crashed here
> Fix RegisterViewModel initialization

- feature/login/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/login/custom_instance_selection/CustomInstanceSelectionScreen.kt
- feature/login/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/login/login/CommonLoginUi.kt
- feature/login/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/login/login/login_options/PasswordBasedLogin.kt
- feature/login/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/login/register/RegisterUi.kt
- feature/metis/conversation/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/metis/conversation/ui/reply/MarkdownTextField.kt
- feature/metis/manage-conversations/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/metis/manageconversations/ui/conversation/PotentiallyIllegalTextField.kt
- feature/metis/manage-conversations/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/metis/manageconversations/ui/conversation/settings/members/ConversationMembersBody.kt
- feature/quiz/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/quiz/question/short_answer/ShortAnswerQuizQuestionUi.kt
- feature/quiz/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/quiz/screens/WaitForQuizStartScreen.kt
Currently many TextFields show a return / newLine key to the user, even for TextFields where this does not make sense (eg for entering names, URLs, emails, etc.)
I scanned for all TextFields in the app and added the appropriate IME actions to them.
> Improve TextField IME actions

- docker/artemis.yml
- docker/artemis_e2e_config.env
- docker/e2e-tests.yml
- docker/mysql.yml
- readme.md
- Fixed end to end test setup locally to get them running again
- Updated README on how to start the end to end tests locally
> `Chore`: Fix End To End Tests Containers

- .gitignore
- .idea/runConfigurations/Docker_for_E2E_Tests.xml
- .idea/runConfigurations/E2E_Tests.xml
- .idea/runConfigurations/Unit_Tests_.xml
- readme.md
- Added run configurations for unit and e2e tests, that can directly be accessed from within Android Studio
- Updated the readme
- Restructured gitignore + add run configurations to git
> `Chore`: Add run configurations for tests

- core/datastore/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/core/datastore/defaults/ArtemisInstances.kt
- feature/metis-test/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/metistest/MetisServiceStub.kt
- feature/metis/conversation/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/metis/conversation/ui/chatlist/MetisSearchPagingSource.kt
- feature/metis/conversation/src/test/kotlin/de/tum/informatics/www1/artemis/native_app/feature/metis/conversation/ui/chatlist/MetisSearchPagingSourceTest.kt
When searching in a channel the server currently sometimes returns posts multiple times. This happens eg if a post has multiple answers in its thread. Conveniently, there was just opened an issue about this in the Artemis repo: https://github.com/ls1intum/Artemis/issues/9709
This caused the Android app to crash due to violation of unique key constraints in the LazyList.
- Filtering out duplicated posts 
- Added tests to ensure functionality
- Updated URL for TestServer1
Eg go to TS1
-> Practical Course: Interactive Learning SS24 
-> #random 
-> Search for "me" 
-> The app does not crash
This closes issue #95.
> Fix crash when searching inside channel

- feature/metis/conversation/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/metis/conversation/ui/thread/MetisThreadUi.kt
This PR is a **hotfix** that fixes an issue, which caused replies in the thread view not to be created correctly. Instead of calling the createReply function the createPost function of ConversationViewModel was called, leading to a post creation instead of a reply creation.
This bug only affects `develop` and has been introduced by the change of MetisThreadUI in #59.
> `Hotfix`: Fix post creation of MetisThreadUI to create replies instead of posts

- feature/settings/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/settings/SettingsScreen.kt
- feature/settings/src/main/res/values/settings_strings.xml
Currently it is very hard / not directly possible to see what server one is currently logged in to.
- Display the server url in the settings
**Out of scope**
I know that the layout is not optimal atm, but I think the whole settings section should be overhauled in  a separate PR.
- Open settings
- Scroll to About section
- See server url
> `Chore`: Display server url in settings

- feature/metis/conversation/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/metis/conversation/ui/ConversationChatListScreen.kt
- feature/metis/conversation/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/metis/conversation/ui/ConversationThreadScreen.kt
Some of the previously integrated updates caused an issue, which resulted in the text field being stuck to the bottom of the screen (see screenshot)
The official insets library is now used to set the bottom padding.
**Before**
**After**
> `Bugfix`: Fix padding for markdown text field in chat

- core/core-test/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/core/test/TestWebsocketProvider.kt
- core/websocket/src/debug/kotlin/de/tum/informatics/www1/artemis/native_app/core/websocket/WebsocketProviderStub.kt
- core/websocket/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/core/websocket/WebsocketProvider.kt
- core/websocket/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/core/websocket/impl/WebsocketProviderImpl.kt
- core/websocket/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/core/websocket/impl/WebsocketTopic.kt
- feature/metis-test/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/metistest/MetisServiceStub.kt
- feature/metis/conversation/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/metis/conversation/service/network/MetisService.kt
- feature/metis/conversation/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/metis/conversation/service/network/impl/MetisServiceImpl.kt
- feature/metis/conversation/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/metis/conversation/ui/ConversationViewModel.kt
- feature/metis/conversation/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/metis/conversation/ui/ConversationWebSocketUpdateUseCase.kt
- feature/metis/manage-conversations/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/metis/manageconversations/ui/conversation/overview/ConversationOverviewViewModel.kt
- feature/metis/shared/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/metis/shared/content/MetisCrudAction.kt
- feature/metis/shared/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/metis/shared/content/MetisPostDTO.kt
- feature/metis/shared/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/metis/shared/content/dto/ConversationWebsocketDto.kt
- feature/metis/shared/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/metis/shared/service/network/ConversationWebsocketExtensions.kt
Currently the user has to manually refresh the conversation to show post updates (such as reactions, mark as resolved) for non-coursewide channels. 
This problem was caused by only subscribing to the coursewide websocket.
This PR will fix #60 
- Subscribe to non-coursewide websocket
- Renamed parameter "channel" to "topic" to match iOS and Web implementations
- Introduced `WebsocketTopic` file to centrally manage the websocket topics
Test for both a coursewide channel (eg tech-support) and a non-coursewide channel (eg groupchat):
- Go to the channel
- Write a message -> is shown in chat
- React to the message -> reaction is shown without the need to manually refresh
- Reply to message in thread with new answer
- Mark answer as "Resolves Post" -> Answer is shown as resolving
As mentioned …
> `Bugfix`: Fix manual refresh for post updates

- app/src/main/java/de/tum/informatics/www1/artemis/native_app/android/db/AppDatabase.kt
- feature/metis-test/build.gradle.kts
- feature/metis-test/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/metistest/paging_source_util.kt
- feature/metis/conversation/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/metis/conversation/ui/post/PostContextBottomSheet.kt
- feature/metis/shared/build.gradle.kts
- feature/metis/shared/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/metis/shared/db/entities/MetisPostContextEntity.kt
- feature/metis/shared/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/metis/shared/db/entities/PostReactionEntity.kt
- feature/metis/shared/src/test/kotlin/de/tum/informatics/www1/artemis/native_app/feature/metis/shared/db/MetisDaoTest.kt
In the hotfix for version [1.0.1](https://github.com/ls1intum/artemis-android/releases/tag/1.0.1) and [1.0.2](https://github.com/ls1intum/artemis-android/releases/tag/1.0.2) the foreign key constraints for reactions were removed. Additionally, the primary key constraints for posts and reactions were altered to include the server_id. These changes were done to prevent the application from crashing. This however introduced the problem that while the app was running without crashes, the data integrity is not given anymore.
Pull Request #58 fixed an issue with the answer threads not being shown. This issue also seemed to be the origin of the failing primary and foreign key constraints. Therefore I reverted the changes to include the previous FK and PK checks as they were.
Closes #62
> `Communication`: Reintroduce foreign key constraints and offline primary keys

- feature/metis/manage-conversations/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/metis/manageconversations/ui/conversation/settings/KickUserDialog.kt
- feature/metis/manage-conversations/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/metis/manageconversations/ui/conversation/settings/PerformActionOnUserDialogs.kt
As described in #168 the kick dialog keeps reappearing after confirming to kick a user from a group/channel.
This PR fixes this behavior by adding the onDismiss function call to the completion function. This is necessary to clear the userActionData, which otherwise would not be set to null and causing the dialog to reappear after the reload.
Furthermore, this PR changes the dialog for groups to the correct one.
This PR fixes #168.
1. Pick a user with moderation rights or create a group
2. Go to the group or channel
3. Navigate to the settings (top right in the chat view)
4. Try removing a member
5. Verify that the dialog does not reappear after clicking on `Remove user`
> `Bugfix`: Fix reappearing kick user dialog

- feature/settings/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/settings/SettingsScreen.kt
- feature/settings/src/main/res/values/settings_strings.xml
The settings screen is currently quite cluttered, and it is difficult to distinguish between buttons and static text. The problems have been described in #123
This PR changes the Preference sections and introduces new Preference entries to make the view more appealing and easier to understand. See the screenshots below. This PR fixes #123
Before:
After:
> Redesign settings screen and remove clutter

- feature/metis/conversation/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/metis/conversation/ui/ConversationThreadScreen.kt
- feature/metis/conversation/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/metis/conversation/ui/ConversationViewModel.kt
As described in #209, after deleting the parent post the user stays in the thread view facing a loading error, because the post is not available anymore.
The onNavigateUp method is now passed down to the view model to be invoked after the parent post got successfully deleted in the thread view. This PR closes #209.
1. Go to the thread view.
2. Delete the Parent Post
3. Verify that you get taken back to the previous screen.
4. Try the same without an internet connection and verify the error dialog is still shown.
5. Try deleting an answer post in the thread view and verify that you are not taken back to the previous screen
6. Try deleting a post outside of the thread view and verify it works like before.
> `Bugfix`: Close thread after deleting Parent Post

- feature/metis/manage-conversations/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/metis/manageconversations/ui/conversation/settings/members/ConversationMembersScreen.kt
In the conversation members overview, the search bar was hardly visible and hidden behind the title.
This closes #218.
Fixed padding
> `Bugfix`: Channel members search bar hardly visible

- feature/metis/manage-conversations/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/metis/manageconversations/ui/conversation/settings/members/ConversationMembersViewModel.kt
- feature/metis/manage-conversations/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/metis/manageconversations/ui/conversation/settings/members/MembersDataSource.kt
Sometimes when scrolling through the members overview, the app would crash.
This closes #215.
- Fixed the code for creating the paging server requests
- Moved MAX_PAGE_SIZE logic to the PagingConfig
1. Go to TS1
2. Course "Artemis Feature Demo Course"
3. Go to channel #random
4. Click the settings icon
5. Scroll down the members list and click "view all members"
6. Scroll down the member list
7. See that the app no longer crashes
8. Hooray!
> `Bugfix`: Fix conversation members overview crash due to duplicate key

- feature/metis/conversation/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/metis/conversation/service/storage/impl/MetisStorageServiceImpl.kt
- feature/metis/conversation/src/test/kotlin/de/tum/informatics/www1/artemis/native_app/feature/metis/conversation/service/storage/impl/MetisStorageServiceTestUpdatePost.kt
The would crash when there were two posts with the same clientPostId in different conversations (which is allowed), and one received an update for post1 while being in the metisContext of post2. This happened due to a small bug in the implementation.
This closes #241 
- Fixed bug
- Added test
Follow steps described in issue and see that the crash no longer happens:
> Steps to reproduce the behavior:
> - Login as test_user_1 on TS1
> - Interactive Learning WS24/25 course
> - Go to channel #random (I think this is required to load the message in this chat)
> - Go back to Conversation Overview
> - Open DM with test_user_20
> - On the web app, as test_user_20
>   - Go to same course and #random
>   - Scroll up to post "testmessage" from Test User 16 Artemis with timestamp 2024-11-03
>   - …
> `Bugfix`: Fix crash when updating post with same clientPostId

- build-logic/convention/src/main/kotlin/commonConfiguration/KotlinAndroid.kt
- core/core-test/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/core/test/test_setup/TestServerConfigurationProvider.kt
- core/datastore/src/debug/kotlin/de/tum/informatics/www1/artemis/native_app/core/datastore/ServerConfigurationServiceStub.kt
- core/datastore/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/core/datastore/ServerConfigurationService.kt
- core/datastore/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/core/datastore/impl/ServerConfigurationServiceImpl.kt
- feature/login/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/login/AccountUi.kt
- feature/login/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/login/instance_selection/InstanceSelectionScreen.kt
- feature/login/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/login/login/LoginUi.kt
- feature/settings/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/settings/SettingsScreen.kt
The current Artemis Android release in the Play Store uses the "Tum" build flavor, which does not allow instance (artemis server) selection. Simply switching the released build flavor to "unrestricted" would have caused already logged in users with weird behaviour (all network calls would fail because it would try to reach the artemis server via localhost; only a logout and sign in again would have resolved this issue).
- Changed the default server for the "unrestricted" flavor to the tum artemis server
- Adapted settings code to rely on the `serverUrl` instead of the duplicated logic with `hasUserSelectedInstance`
- Removed now no longer needed code `hasUserSelectedInstance`
- Fixed bug introduced by https://github.com/ls1intum/artemis-android/pull/222, as it removed the …
> `Chore`: Set tum artemis server as default

- feature/metis/conversation/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/metis/conversation/ui/ConversationChatListScreen.kt
- feature/metis/conversation/src/main/res/values/conversation_strings.xml
The member count is not shown in the Top bar like it is shown on iOS.
The Top Bar title of the chat has been changed to a column to also show the number of members if the conversation is not a DM chat.
1. Verify that the member count is represented correctly in a chat
2. Verify that it is not shown for DM chats
> `Improvement`: Add member count to chat top bar title

- feature/push/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/push/ui/PushNotificationSettingCategoriesListUi.kt
When scrolling to the end of the notification settings, the floating action button to save the changes is placed right above the switch of the last notification category making it hard for users to reach this switch.
A spacer has been added below the list to increase the padding after the last category. This allows users to reach the switch more easily.
Scroll to the end of the notification settings and verify that there is enough space now to reach both, the last switch and the floating action button.
> `Improvement`: Increase space below notification settings categories

- feature/metis/conversation/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/metis/conversation/ui/reply/MarkdownTextField.kt
- feature/metis/conversation/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/metis/conversation/ui/reply/ReplyTextField.kt
When pressing the right half of the ReplyTextField with a short draft message, the keyboard did not pop up. 
- Fix the bug
- Refactorings
- Go to a chat with a short draft message (or create a new one)
- Click anywhere on the textfield
- -> Notice that the keyboard shows
This is a recording of the problem how it previously was:
https://github.com/user-attachments/assets/645a3d06-79de-4f4e-9bf7-db570973ee9f
> `Bugfix`: Show keyboard on textfield press

- feature/push/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/push/communication_notification_model/PushCommunicationDao.kt
- feature/push/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/push/push_module.kt
- feature/push/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/push/service/impl/notification_manager/CommunicationNotificationManagerImpl.kt
The user would get a notification when replying to its own post in a non-DM chat. 
While the root cause for this is on the server-side, I decided to add a workaround for the meantime.
This closes #326 
- Check whether author of post notification is the app user and discard the notification in this case
- In the Android app enable notifications for test_user_1
- On the web app, create a post in a channel with test_user_1
- -> No notification on the android app
- On the web app, create a new answer post to the latter post (using test_user_1 again)
- -> Notice that no notification is received anymore for own answer post
> `Bugfix`: Add workaround for notifaction for own answer

- core/ui/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/core/ui/material/colors/ComponentColors.kt
- feature/metis/manage-conversations/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/metis/manageconversations/ui/conversation/browse_channels/BrowseChannelsScreen.kt
The Browse Channels Screen does not look like the iOS app and feels cluttered.
This is just a very small PR, that aligns the design of the Browse Channels screen with the design used in the iOS app. 
The ChannelChatItem used in the list was modified and wrapped in a Card.
Make sure it looks good.
> `Improvement`: Redesign Browse Channels

- feature/metis/conversation/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/metis/conversation/ui/chatlist/MetisPostListHandler.kt
- feature/metis/manage-conversations/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/metis/manageconversations/ui/conversation/overview/ConversationOverviewViewModel.kt
- feature/metis/shared/src/debug/kotlin/de/tum/informatics/www1/artemis/native_app/feature/metis/shared/ConversationServiceStub.kt
- feature/metis/shared/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/metis/shared/service/network/ConversationService.kt
- feature/metis/shared/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/metis/shared/service/network/impl/ConversationServiceImpl.kt
- feature/push/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/push/service/impl/PushNotificationHandlerImpl.kt
- feature/push/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/push/service/impl/notification_manager/NotificationTargetManager.kt
- feature/push/src/test/kotlin/de/tum/informatics/www1/artemis/native_app/feature/push/PushNotificationVisibleContextTest.kt
This PR fixes three bugs related to receiving new posts:
1. When receiving newly created messages in a chat the conversation's unread counter was not updated as expected. After reloading the unread counter would show these newly received messages as unread again. This PR closes #226 
2. Notifications about a chat were received when in that chat.
3. In the ChatList when receiving a new post, the ChatList did not scroll to the new post automatically
- Added `markConversationAsRead` API
- Calling this API when the chat is visible
- Correct logic for checking whether notification target is visible
- Fix scrolling down when new post arrives in the ChatList
1. Activate notifications
1. Go to any chat with no unread messages
4. In the same chat, write  a message with another user from a …
> `Bugfix`: Multiple bug fixes related to receiving new post updates

- feature/metis/conversation/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/metis/conversation/ui/reply/util/MarkdownStyleUtil.kt
- feature/metis/conversation/src/test/kotlin/de/tum/informatics/www1/artemis/native_app/feature/metis/conversation/TextFieldValueExtension.kt
- feature/metis/conversation/src/test/kotlin/de/tum/informatics/www1/artemis/native_app/feature/metis/conversation/ui/reply/MarkdownListContinuationUtilTest.kt
- feature/metis/conversation/src/test/kotlin/de/tum/informatics/www1/artemis/native_app/feature/metis/conversation/ui/reply/util/MarkdownStyleUtilTest.kt
When selecting some text in the ReplyTextField, and the selection was done by dragging from right to left, and the user then applied some markdown, the app crashed.
- Using `selection.min/max` instead of `selection.start/end` in substring creation
- Added tests
- Go to any chat 
- Type some text into the ReplyTextField (at least two words)
- Make a reverse selection by
- long pressing on the second word
- while still pressing on the screen, drag to the left to the first word
- release press
- Press any formatting option
- No crash
How to reproduce the bug (here with the app crashing prior to this bugfix):
https://github.com/user-attachments/assets/e556d480-b3f1-4609-926a-f16c1459c4d0
> `Bugfix`: Apply markdown for reverse selection

- core/ui/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/core/ui/common/course/CourseItem.kt
- core/ui/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/core/ui/compose/BackgroundColorBasedTextColor.kt
See https://github.com/ls1intum/Artemis/pull/10375
Adjust the course title text color based on the background
- Go to a course overview
- Notice that the title colors are either black or white, based on the course card color
> `Feature`: Add contrast based course title text color

- core/ui/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/core/ui/markdown/link_resolving/MarkdownLinkResolverImpl.kt
Currently, when clicking on a link in the chat to open an attachment, the thread gets opened as both click events are triggered; see #271.
This PR adds a workaround to the MarkdownLinkResolver to cancel pending click events to prevent the views onClick function from being called.
This PR fixes #271 
1. Go to a chat that contains attachment links (`random` in `Practical Course: Interactive Learning SS24` on TS3)
2. Click on the link and verify that only the pdf viewer shows up and there is no navigation to the thread.
> `Bugfix`: Fix link click conflict with post click action

- feature/metis/conversation/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/metis/conversation/ui/post/PostWithBottomSheet.kt
Currently, a horizontal padding of 24.dp is applied to posts in the chat.
This PR fixes the issue described above.
Go to the chat and make sure that the post items look like they used to.
> `Bugifx`: Fix Post horizontal Padding

- app/src/main/java/de/tum/informatics/www1/artemis/native_app/android/app_module.kt
- app/src/main/java/de/tum/informatics/www1/artemis/native_app/android/ui/MainActivity.kt
- app/src/main/java/de/tum/informatics/www1/artemis/native_app/android/ui/RootNavGraph.kt
- core/common/build.gradle.kts
- core/common/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/core/common/app_version/AppVersion.kt
- core/common/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/core/common/app_version/AppVersionProvider.kt
- core/common/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/core/common/app_version/NormalizedAppVersion.kt
- core/common/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/core/common/common_module.kt
- core/common/src/test/kotlin/de/tum/informatics/www1/artemis/native_app/core/common/app_version/NormalizedAppVersionTest.kt
- core/core-test/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/core/test/core_test_modules.kt
- feature/force-update/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/force_update/repository/UpdateRepository.kt
- feature/force-update/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/force_update/repository/UpdateUtil.kt
- feature/force-update/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/force_update/service/UpdateService.kt
- feature/force-update/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/force_update/ui/UpdateNavGraph.kt
- feature/force-update/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/force_update/ui/UpdateScreen.kt
- feature/force-update/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/force_update/update_module.kt
- feature/force-update/src/test/kotlin/de/tum/informatics/www1/artemis/native_app/feature/force_update/UpdateUtilTest.kt
- feature/push/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/push/push_module.kt
- feature/push/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/push/service/impl/PushNotificationConfigurationServiceImpl.kt
- feature/push/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/push/service/impl/UploadPushNotificationDeviceConfigurationWorker.kt
- feature/push/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/push/service/network/NotificationSettingsService.kt
- feature/push/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/push/service/network/impl/NotificationSettingsServiceImpl.kt
- feature/push/src/test/kotlin/de/tum/informatics/www1/artemis/native_app/feature/push/PushNotificationSettingsE2eTest.kt
- feature/quiz/src/test/kotlin/de/tum/informatics/www1/artemis/native_app/feature/quiz/QuizPracticeParticipationE2eTest.kt
- feature/settings/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/settings/ui/SettingsNavGraph.kt
- feature/settings/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/settings/ui/SettingsScreen.kt
With a recent API change, the server expects the app version to be send along the push notification registration call. See https://github.com/ls1intum/Artemis/pull/10384
- Introduce `AppVersion` and `AppVersionProvider` to easily access the app version in the app without having to pass it all the way from the `app` module
- Add `NormalizedAppVersion` to be used in modified API call and in the force-update feature
- Added unit tests
See that updating the push notification settings still works as expected
> `Feature`: Add version code to push notification registrattion

- core/ui/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/core/ui/compose/OnTrueLaunchedEffect.kt
- feature/dashboard/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/dashboard/ui/CoursesOverview.kt
- feature/dashboard/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/dashboard/ui/SurveyHint.kt
- feature/metis/conversation/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/metis/conversation/ui/chatlist/MetisPostListHandler.kt
- feature/metis/conversation/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/metis/conversation/ui/reply/ReplyTextField.kt
There was a bug where the requested AutoCompletionType did not reset after removing the tagging character.
This PR fixes #451 
- When there are not AutoCompletionHints shown, also reset the requested type
- Refactoring
- Introduce `OnTrueLaunchedEffect`
1. Go to any chat
2. Click on the mention button in the ReplyTextField
3. Click on "Lectures" in the popup
4. See that only lectures are shown
5. Remove the inserted "#" character via backspace
6. Type "#" again
7. See that all AutoCompletionTypes are shown
> `Bugfix`: Autocompletion type does not reset

- feature/metis/manage-conversations/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/metis/manageconversations/ui/conversation/settings/members/ConversationMembersBody.kt
- feature/metis/manage-conversations/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/metis/manageconversations/ui/conversation/settings/members/ConversationMembersViewModel.kt
- feature/metis/manage-conversations/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/metis/manageconversations/ui/conversation/settings/members/MembersDataSource.kt
There was a bug when scrolling through a conversations members list. After scrolling down a bit, the user could not scroll back to the top again.
This PR closes #445 
- Added `prevKey` to Paging result
- For some reason I had to also change the default Page size, because with `PAGE_SIZE = 10` this seemed to introduce a new bug when the user was scrolling really fast.
1. Go to any chat
2. Go to the chat's settings
3. Click on "Show all members"
4. Scroll up and down the members list
5. No weird behaviour
https://github.com/user-attachments/assets/9e77eda5-95c4-4ab0-b5cd-cdc0f3b37a27
> `Bugfix`: Fix members scrolling bug

- core/model/build.gradle.kts
- core/model/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/core/model/account/Account.kt
- core/model/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/core/model/account/AccountAuthority.kt
- core/model/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/core/model/account/BaseAccount.kt
- core/model/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/core/model/account/User.kt
- core/model/src/test/kotlin/de/tum/informatics/www1/artemis/native_app/core/model/account/AccountAuthorityTest.kt
- feature/metis/shared/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/metis/shared/content/dto/CourseUser.kt
- feature/metis/shared/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/metis/shared/content/dto/conversation/ConversationUser.kt
- feature/push/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/push/push_module.kt
- feature/push/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/push/ui/PushNotificationLocalization.kt
- feature/push/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/push/ui/PushNotificationSettingCategoriesListUi.kt
- feature/push/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/push/ui/PushNotificationSettingsUi.kt
- feature/push/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/push/ui/PushNotificationSettingsViewModel.kt
- feature/push/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/push/ui/model/PushNotificationSettingUtil.kt
- feature/push/src/main/res/values/push_notification_settings_strings.xml
- feature/push/src/test/kotlin/de/tum/informatics/www1/artemis/native_app/feature/push/PushNotificationSettingsE2eTest.kt
- feature/push/src/test/kotlin/de/tum/informatics/www1/artemis/native_app/feature/push/ui/model/PushNotificationSettingUtilTest.kt
In Android, we displayed all notification settings as toggles in the notifications settings page, even if some of them should not support push notifications, or are not available to the user because of their role (eg students could change settings  for "Instructor Notifications")
This PR closes #439 
- Hide notifications that are not relevant for push notifications (ssh, vcs-token, data-export)
- Hide notifications based on the user's authorities
- Extracted localization into `PushNotificationLocalization`
- Extracted filtering logic into new `PushNotificationSettingUtil`
- Added tests
1. Log in as a student and see that only relevant notification settings are shown
2. Log in as a tutor/editor/instructor and see that the authority based notifications are shown
> `Improvement`: Only show relevant push notification settings

- feature/metis/manage-conversations/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/metis/manageconversations/ui/conversation/overview/ConversationList.kt
- feature/metis/manage-conversations/src/main/res/values/conversation_overview_strings.xml
- feature/metis/manage-conversations/src/test/kotlin/de/tum/informatics/www1/artemis/native_app/feature/metis/manageconversations/overview/ConversationOverviewE2eTest.kt
The conversation count is currently missing in the conversation overview list, see #479 
This PR adds a small change, that introduces conversation section counts for all sections except the saved post section.
Make sure the count is correctly reflected.
> `Improvement`: Add section count to conversation overview

- app/src/main/AndroidManifest.xml
- feature/push/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/push/communication_notification_model/PushCommunicationDao.kt
- feature/push/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/push/communication_notification_model/PushCommunicationEntity.kt
- feature/push/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/push/notification_model/ArtemisNotification.kt
- feature/push/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/push/push_module.kt
- feature/push/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/push/service/CommunicationNotificationManager.kt
- feature/push/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/push/service/impl/PushNotificationHandlerImpl.kt
- feature/push/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/push/service/impl/notification_manager/BaseCommunicationNotificationReceiver.kt
- feature/push/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/push/service/impl/notification_manager/CommunicationNotificationManagerImpl.kt
- feature/push/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/push/service/impl/notification_manager/MiscNotificationManager.kt
- feature/push/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/push/service/impl/notification_manager/ReplyReceiver.kt
- feature/push/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/push/service/impl/notification_manager/UpdateReplyNotificationWorker.kt
- feature/push/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/push/service/impl/notification_manager/delete/DeleteNotificationReceiver.kt
- feature/push/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/push/service/impl/notification_manager/mark_as_read/MarkAsReadReceiver.kt
- feature/push/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/push/service/impl/notification_manager/mark_as_read/MarkConversationAsReadWorker.kt
- feature/push/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/push/service/impl/notification_manager/reply/ReplyReceiver.kt
- feature/push/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/push/service/impl/notification_manager/reply/UpdateReplyNotificationWorker.kt
- feature/push/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/push/service/impl/notification_manager/util/NotificationTargetManager.kt
- feature/push/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/push/service/impl/notification_manager/util/bitmap_util.kt
Currently, the "Mark as read" action in a notification did just remove the notification from the local notification database. The unread counter of the conversation however did not update accordingly.
- Created new Worker and Receiver for the markAsRead action
- Restructorings and Refactorings on the way of related notification code
1. Enable notifications
2. Receive a new post notification (eg by writing a new post from another user in the webapp)
3. Click on "Mark as read" in the notification
4. Notice that the unread counter of the conversation is updated accordingly
https://github.com/user-attachments/assets/0c66a5e1-0ab0-446d-ace9-6f08e2563a92
> `Improvement`: Update unread counter when clicking notification "Mark as read"

- .github/workflows/compile.yml
- .github/workflows/e2e-test.yml
- .github/workflows/unit-test.yml
- docker/e2e-tests.yml
- docker/mysql.yml
- feature/dashboard/src/test/kotlin/de/tum/informatics/www1/artemis/native_app/feature/dashboard/DashboardE2eTest.kt
- feature/metis/conversation/src/test/kotlin/de/tum/informatics/www1/artemis/native_app/feature/metis/conversation/service/network/impl/SavedPostServiceImplE2eTest.kt
- readme.md
We want to reset the artemis mySQL database, because we create many courses with our e2e tests. Without this reset, there would be many courses piling up, slowing down the tests (and causing some of them to fail / time out).
A similar approach was already done previously in https://github.com/ls1intum/Artemis/pull/8044.
This PR closes #169 and #370 
- Added removal of mysql docker volume to e2e workflow
- Just to be sure we do not mess with other workflows that rely on the persistence of the volume, we created a separate one just for the android e2e tests
> `Chore`: Fix e2e tests reset database

- core/data/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/core/data/service/Api.kt
- docker/create_test_users.sh
The Artemis docker image `latest` (see https://github.com/ls1intum/Artemis/pkgs/container/artemis), now uses the API endpoints of Artemis 8.0. As our e2e tests use this docker image, we need to adapt the `Api`  to use the 8.0 endpoints by default.
> `Chore`: Update api routes for e2e tests

- core/ui/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/core/ui/material/colors/PostColors.kt
- feature/metis/conversation/shared/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/metis/conversation/shared/ui/post/PostMainContent.kt
The post title on mobile clients was previously using a blue color to align with the web. However, as discussed in [this PR](https://github.com/ls1intum/artemis-ios/pull/305), this color choice could be misinterpreted as indicating a clickable link. This behavior was inconsistent with the intended design and could lead to user confusion.
The title color change to base text color
1. Log in to Artemis.
2. Navigate to a course with active communication.
3. Open the announcement channel.
4. Verify that the post title: Uses the base text color (not blue).
> `Chore`: Adapt Announcement Title Styling

- app/src/tum/AndroidManifest.xml
- app/src/unrestricted/AndroidManifest.xml
- build-logic/convention/src/main/kotlin/commonConfiguration/KotlinAndroid.kt
- core/data/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/core/data/service/Api.kt
- core/datastore/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/core/datastore/defaults/ArtemisInstances.kt
- core/datastore/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/core/datastore/impl/ServerConfigurationServiceImpl.kt
- core/ui/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/core/ui/deeplinks/ArtemisDeeplink.kt
- readme.md
We should use the new tum artemis url now
- Using new tum artemis url
- Replace legacy url on the fly if previously configured
- on develop: Login to the TUM instance
- checkout this PR: 
- see that user is not logged out
- see that url is now artemis.tum.de (eg in settings)
- see that api calls still work
> `Chore`: Switch to artemis.tum.de instance

- feature/course-view/src/debug/kotlin/de/tum/informatics/www1/artemis/native_app/feature/courseview/MessagingScreenshots.kt
- feature/metis/conversation/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/metis/conversation/service/network/MetisService.kt
- feature/metis/conversation/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/metis/conversation/service/network/impl/MetisServiceImpl.kt
- feature/metis/conversation/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/metis/conversation/ui/ConversationChatListScreen.kt
- feature/metis/conversation/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/metis/conversation/ui/ConversationViewModel.kt
- feature/metis/conversation/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/metis/conversation/ui/chatlist/ConversationChatListUseCase.kt
- feature/metis/conversation/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/metis/conversation/ui/chatlist/MetisRemoteMediator.kt
- feature/metis/conversation/src/main/res/values/conversation_strings.xml
- feature/metis/conversation/src/test/kotlin/de/tum/informatics/www1/artemis/native_app/feature/metis/conversation/ConversationMessagesE2eTest.kt
- feature/metis/shared/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/metis/shared/content/MetisFilter.kt
Currently, there is no filtering for messages available as in the iOS app.
This PR adds a filtering option to the dropdown menu in conversations and adds filtering logic. 
Filtering is available for own, reacted, pinned and unresolved messages.
1. Go into any channel
2. Click the more icon in the top bar
3. Click on Filter Messages
4. Verify the filtering dropdown menu is shown 
5. Click on the options and verify the correct messages are shown.
> `Feature`: Filter messages in chats

- feature/faq/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/faq/ui/FaqArtemisMarkdownTransformer.kt
There was a bug in the file upload API that required changes to the returned path URL after a file upload. As the Android FAQ  implementation assumed that was a feature and not a bug, we need to undo these URL adjustments.
This closes #526 
Test with a server that has  https://github.com/ls1intum/Artemis/pull/10622 merged (eg the develop branch). You can deploy the develop branch with Helios.
- Webapp: Create a new FAQ with an image (or use TS2 > Test Course Martin Felber)
- Navigate to the FAQ in the Android app
- Verify that you can see the image in the FAQ details page
> `Chore`: Use new file upload URL for FAQs

- feature/login-test/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/login/test/TestLoginUtil.kt
- feature/metis/manage-conversations/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/metis/manageconversations/ui/conversation/settings/overview/ConversationOtherSettings.kt
- feature/metis/manage-conversations/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/metis/manageconversations/ui/conversation/settings/overview/ConversationSettingsBody.kt
- feature/metis/manage-conversations/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/metis/manageconversations/ui/conversation/settings/overview/ConversationSettingsViewModel.kt
- feature/metis/manage-conversations/src/main/res/values/conversation_settings_strings.xml
- feature/metis/manage-conversations/src/test/kotlin/de/tum/informatics/www1/artemis/native_app/feature/metis/manageconversations/settings/ChannelSettingsE2eTest.kt
- feature/metis/manage-conversations/src/test/kotlin/de/tum/informatics/www1/artemis/native_app/feature/metis/manageconversations/settings/ConversationSettingsBaseE2eTest.kt
- feature/metis/shared/src/debug/kotlin/de/tum/informatics/www1/artemis/native_app/feature/metis/shared/ConversationServiceStub.kt
- feature/metis/shared/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/metis/shared/service/network/ConversationService.kt
- feature/metis/shared/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/metis/shared/service/network/impl/ConversationServiceImpl.kt
Android app currently lacks the ability to toggle channel privacy,  currently web app have this function.. Adding this option enables users to seamlessly switch between public and private channels, improving flexibility and access control.
The ability to toggle channel privacy has been added. This feature is integrated into the Channel Settings.
It allows switching a public channel to private and vice versa. I
nformative confirmation dialogs have also been implemented.
1 user with moderation rights
Open course activated Channel 
- Create a new public channel (or use existing one )  and from channel setting toggle the privacy
- Create a new private channel (or use existing one ) and from channel setting toggle the privacy
In each case should display a pop up to inform user about the …
> `Feature`: Toggle Channel Privacy

- feature/metis/manage-conversations/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/metis/manageconversations/ui/common/ConversationUserSelectionScreen.kt
- feature/metis/manage-conversations/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/metis/manageconversations/ui/common/PotentiallyIllegalTextField.kt
- feature/metis/manage-conversations/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/metis/manageconversations/ui/conversation/create_channel/CreateChannelScreen.kt
- feature/metis/manage-conversations/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/metis/manageconversations/ui/conversation/create_personal_conversation/CreatePersonalConversationScreen.kt
- feature/metis/manage-conversations/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/metis/manageconversations/ui/conversation/settings/add_members/ConversationAddMembersScreen.kt
- feature/metis/manage-conversations/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/metis/manageconversations/ui/conversation/settings/overview/ConversationInfoSettings.kt
- feature/metis/manage-conversations/src/test/kotlin/de/tum/informatics/www1/artemis/native_app/feature/metis/manageconversations/members/ConversationAddMemberSettingsE2eTest.kt
- feature/metis/manage-conversations/src/test/kotlin/de/tum/informatics/www1/artemis/native_app/feature/metis/manageconversations/overview/CreateConversationE2eTest.kt
There were two very similar composables as described in #376.
This PR introduces a new Composable `ConversationUserSelectionScreen`, which holds the common logic of both views. 
This PR fixes #376 
1. Go to the conversation overview.
2. Create a new chat.
3. Add members, click the create button and make sure the chat is correctly created.
4. Head over to the newly created chat and go to the conversation settings.
5. Click on add members.
6. Add new members and make sure everything works as expected.
> `Chore`: Combine `ConversationAddMembersScreen` and `CreatePersonalConversationScreen`

- core/ui/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/core/ui/Spacings.kt
- core/ui/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/core/ui/compose/ArtemisPopupSurface.kt
- feature/metis/conversation/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/metis/conversation/ui/reply/autocomplete/AutoCompleteHint.kt
- feature/metis/conversation/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/metis/conversation/ui/reply/autocomplete/AutoCompletionUseCase.kt
- feature/metis/conversation/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/metis/conversation/ui/reply/autocomplete/ReplyAutoCompletePopup.kt
- feature/metis/conversation/src/test/kotlin/de/tum/informatics/www1/artemis/native_app/feature/metis/conversation/BaseChatUITest.kt
- feature/metis/conversation/src/test/kotlin/de/tum/informatics/www1/artemis/native_app/feature/metis/conversation/ConversationAutoCompletionE2eTest.kt
- feature/metis/shared/src/debug/kotlin/de/tum/informatics/www1/artemis/native_app/feature/metis/shared/ConversationServiceStub.kt
- feature/metis/shared/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/metis/shared/service/network/ConversationService.kt
- feature/metis/shared/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/metis/shared/service/network/impl/ConversationServiceImpl.kt
- feature/metis/shared/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/metis/shared/ui/ConversationExtensions.kt
- feature/metis/shared/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/metis/shared/ui/member_selection/MemberSearchWithDropdownPopup.kt
Previously we did not display the users profile pictures when searching for user mentions. This was inconsistent to the other places within the app.
This PR closes #329 
- Use different API endpoint for fetching user mention suggestions (that includes the imageUrls)
- Display hint if the search query is too short
1. Go to any chat
2. Start a user mention by typing "@" or via the mention icon button
3. See that a hint is shown that you need to type at least 3 characters
4. When typing more than 3 chars, the search results are shown with a profile picture
> `Feature`: Show user profile pictures in mention search

- core/ui/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/core/ui/compose/RoundGreenCheckbox.kt
- core/ui/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/core/ui/material/colors/ComponentColors.kt
- feature/lecture-view/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/lectureview/LectureOverviewTab.kt
- feature/lecture-view/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/lectureview/lecture_units/LectureUnitHeader.kt
The lecture view headers are inconsistent with the exercise overview.
This PR changes the lecture view slightly to make it more consistent with the exercise view and introduces the proposed changes to the checkboxes.
Go to a lecture and make sure it still looks good.
> `Improvement`: Lecture view adjustments

- feature/metis/conversation/saved-posts/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/metis/conversation/saved_posts/saved_posts_module.kt
- feature/metis/conversation/saved-posts/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/metis/conversation/saved_posts/ui/SavedPostsScreen.kt
- feature/metis/conversation/saved-posts/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/metis/conversation/saved_posts/ui/SavedPostsViewModel.kt
- feature/metis/conversation/saved-posts/src/main/res/values/saved_posts_strings.xml
- feature/metis/conversation/saved-posts/src/test/java/de/tum/informatics/www1/artemis/native_app/feature/metis/conversation/saved_posts/SavedPostsScreenUiTest.kt
- feature/metis/manage-conversations/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/metis/manageconversations/ui/conversation/overview/ConversationList.kt
- feature/metis/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/metis/ui/SinglePageConversationBody.kt
There were some padding and window insets issues with the redesigned saved posts screen:
- Extra padding around status selection row
- Window insets at bottom are not considered correctly
- Made the padding of the status selection row smaller
- Fixed window insets for the navigationbar
- Made saved messages section in conversation overview bigger
- Smaller UI refactorings
See that the padding looks nice now
Now:
> `Improvement`: Fix saved posts paddings

- build-logic/convention/src/main/kotlin/commonConfiguration/KotlinAndroid.kt
- core/datastore/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/core/datastore/impl/ServerConfigurationServiceImpl.kt
- feature/login/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/login/custom_instance_selection/CustomInstanceSelectionScreen.kt
After installing the Android app, the default serverUrl was set to the tum instance, but the slash was missing from the serverUrl. This caused a bug where file uploads incorrectly formatted the path to the uploaded file.
This PR fixes this bug
- Uninstall and re-install the app
- Upload a file to a chat
- See that the uploaded image can be viewed
> `Bugfix`: Fix fileupload url

- feature/faq/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/faq/ui/overview/FaqOverviewUi.kt
The was no clear indicator when the FAQ answer has been truncated in the overview list screen.
Added a fading background similar to iOS
- Go to a course with FAQs (or create some)
- See that the fade effect behind the "Read more" button looks good
> `Improvement`: Add fading background for FAQ similar to iOS

- core/ui/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/core/ui/compose/ArtemisWebView.kt
- feature/exercise-view/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/exerciseview/home/overview/ExerciseOverviewTab.kt
- feature/exercise-view/src/main/res/values/exercise_view_strings.xml
The exercise view has no label to indicate the start of the problem statement and the problem statement comes with a gray background, which does not fit the rest of the view.
This PR fixes the problems described above, by adding a new label and injecting a javascript code block to change the background color.
Make sure everything looks good and works as expected.
> `Improvement`: Exercise view adjustments

- feature/push/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/push/notification_model/ArtemisNotification.kt
Due to a recent change in the backend, the date included in the push-notifications is in a different format. This format is incompatible with the standard serializer.
This PR adds a custom serializer, that deserializes the push-notification correctly.
Dates in this format `2025-05-04T11:28:18.762036099Z[Etc/UTC]` are now converted to this format `2025-05-04T11:28:18.762036099Z` before deserialization.
1. Make sure push notifications for messages are enabled. (Go to a course on the web app and check the course settings).
2. Go to a channel on the web app.
3. Send a message
4. Verify, that a push notification gets delivered correctly.
> `Bugfix`: Fix Push Notification Serialization Error

- feature/push/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/push/ui/PushNotificationSettingsUi.kt
- feature/push/src/main/res/values/push_notification_settings_strings.xml
With the new course-specific notification system it is not possible to fine-grain the global notification settings.
This PR removes the options for the notification settings.
Make sure everything works as expected.
> `Improvement`: Disable Notification Settings categories

- core/ui/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/core/ui/common/DataStateUi.kt
- core/ui/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/core/ui/common/EmptyListHint.kt
- feature/course-registration/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/courseregistration/RegisterForCourseUi.kt
- feature/metis/conversation/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/metis/conversation/ui/chatlist/MetisChatList.kt
- feature/metis/conversation/src/main/res/values/conversation_strings.xml
As described in #319 there a lists that do not contain any information when they are empty. 
Although most of the lists already have an empty list view, that provides information if a list is empty this PR adds the empty list hints for the remaining views that do not have such a hint yet.
This PR closes #319 
1. Verify that when there is no internet an icon is now shown.
2. Verify that all lists have an icon and a text when they are empty.
> `Improvement`: Show more information in empty lists

- feature/metis/conversation/shared/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/metis/conversation/shared/ui/post/PostMainContent.kt
- feature/metis/conversation/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/metis/conversation/service/storage/impl/MetisStorageServiceImpl.kt
- feature/metis/shared/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/metis/shared/content/dto/AnswerPost.kt
- feature/metis/shared/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/metis/shared/db/MetisDao.kt
- feature/metis/shared/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/metis/shared/db/pojo/AnswerPostPojo.kt
- feature/metis/shared/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/metis/shared/db/pojo/PostPojo.kt
- feature/metis/shared/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/metis/shared/ui/common/UserRoleBadge.kt
- feature/metis/shared/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/metis/shared/ui/profile_picture/UserProfileDialog.kt
There was an issue that the user role badge as a tutor sometimes was stuck on displaying "Student" even though the user is a "Tutor". After reloading the issue was gone. See https://github.com/ls1intum/Artemis/issues/10824
Additionally, the role badge shortly showed "Student" when sending a message, then it switched back to the correct author role.
Fixed by removing the `remember` statement of the authorRole. Instead we handle remembering the author role for updates now in the database.
Additionally, I made the userRole nullable, so that we do not display any role badge when the role is null (instead of displaying "Student")
1. Login as a tutor (or instructor)
2. Go to any chat
3. Write a post
4. See that author role badge is shown correctly
5. Also test for creating answer posts and …
> `Bugfix`: Show correct user role badge after sending message

- feature/metis/conversation/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/metis/conversation/ui/reply/MarkdownTextField.kt
There was a problem with the scrolling behaviour of the reply TextField. This PR closes #617 
Remove the manual scroll behaviour
- Go to a chat
- Write a message spanning multiple lines
- When the text is long enough, you should see that the textfield becomes scrollable
- Confirm that there is no weird scrolling behaviour anymore. When typing, the text at the cursor position is always visible.
https://github.com/user-attachments/assets/2172ee02-1b99-4a37-9268-14feedab3b4a
> `Bugfix`: Fix scrolling in ReplyTextField

- core/ui-test/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/core/ui/test/BottomSheetClickWorkaroundTheme.kt
- core/ui/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/core/ui/LocalSegmentedButtonBaseShapeProvider.kt
- feature/metis/conversation/saved-posts/src/test/java/de/tum/informatics/www1/artemis/native_app/feature/metis/conversation/saved_posts/SavedPostsScreenUiTest.kt
- feature/metis/conversation/src/test/kotlin/de/tum/informatics/www1/artemis/native_app/feature/metis/conversation/BaseChatUITest.kt
- feature/metis/conversation/src/test/kotlin/de/tum/informatics/www1/artemis/native_app/feature/metis/conversation/ConversationAnswerMessagesUITest.kt
- feature/metis/conversation/src/test/kotlin/de/tum/informatics/www1/artemis/native_app/feature/metis/conversation/ConversationMessagesUITest.kt
- feature/metis/conversation/src/test/kotlin/de/tum/informatics/www1/artemis/native_app/feature/metis/conversation/ui/reply/ReplyTextFieldVisibilityUITest.kt
- feature/metis/manage-conversations/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/metis/manageconversations/ui/conversation/create_channel/CreateChannelScreen.kt
- feature/metis/manage-conversations/src/test/kotlin/de/tum/informatics/www1/artemis/native_app/feature/metis/manageconversations/overview/CreateChannelE2eTest.kt
We had to disable many tests because of a bug in the robolectric testing framework. This bug causes click events to not trigger when performed on a composable with uneven corner radii.
This PR closes #495 
Implemented workarounds for this issue.
See that tests pass
> `Chore`: Add workaround for robolectric bug

- core/ui/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/core/ui/common/DataStateUi.kt
- feature/metis/conversation/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/metis/conversation/service/storage/MetisStorageService.kt
- feature/metis/conversation/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/metis/conversation/service/storage/impl/MetisStorageServiceImpl.kt
- feature/metis/conversation/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/metis/conversation/ui/thread/ConversationThreadUseCase.kt
- feature/push/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/push/communication_notification_model/PushCommunicationDao.kt
- feature/push/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/push/notification_model/target/CommunicationPostTarget.kt
- feature/push/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/push/service/impl/notification_manager/CommunicationNotificationManagerImpl.kt
- feature/push/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/push/service/impl/notification_manager/util/NotificationTargetManager.kt
When clicking on a notification for a reply, the thread failed to load. This was for two main problems:
1. When storing the received notifications, we only stored the answerPostId for answer notifications. However, we need the id of the base post to navigate to the thread with the newly received answer.
2. When navigation to an older thread, the thread always failed to load. This is not directly related to the notification navigation, but could also be observed when receiving a notification about a new answer to an older post. This problem is also reproducible by saving an old post (go >20 posts up in the chat), and clicking on the post in the "Saved Messages" screen. Then the thread would also fail to load.
This PR closes #627.
For fixing 1. :
- Store the basePost id as the `parentId` …
> `Bugfix`: Navigate to post after reply notification

- feature/push/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/push/communication_notification_model/CommunicationNotificationPlaceholderContent.kt
- feature/push/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/push/communication_notification_model/PushCommunicationDao.kt
- feature/push/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/push/service/impl/notification_manager/CommunicationNotificationManagerImpl.kt
- feature/push/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/push/service/impl/notification_manager/reply/ReplyReceiver.kt
- feature/push/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/push/service/impl/notification_manager/reply/UpdateReplyNotificationWorker.kt
When using the quick-reply feature to reply to a notification, the answer was not displayed in the notification (as expected eg from WhatsApp).
This PR closes #216 
1. Activate push notifications on Android
2. Receive a communication notification
3. Click "Reply" and write a reply to that notification
4. See that after sending the quick-reply, this reply text is also shown as a second part of the notification
> `Improvement`: Show notification quick-reply texts

- core/ui/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/core/ui/alert/TextAlertDialog.kt
- feature/course-view/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/courseview/ui/course_overview/CourseScaffold.kt
The color adaption was missing for bottom navigation and some alerts.
The bottom navigation and Alert colors aligned
Open app click to settings.
Go to notification setting and toggle, see sync alert is now on the color scheme we use.
Go back to course, check bottom nagivation the indicator is transparent and selected tab is on primary color
> `Improvement`: Adapt navigation  bar colors

- feature/exercise-view/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/exerciseview/home/overview/ExerciseOverviewTab.kt
- feature/lecture-view/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/lectureview/AttachmentsSection.kt
- feature/lecture-view/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/lectureview/LectureOverviewTab.kt
- feature/lecture-view/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/lectureview/LectureScreenBody.kt
- feature/lecture-view/src/main/res/values/lecture_strings.xml
- feature/lecture-view/src/test/kotlin/de/tum/informatics/www1/artemis/native_app/feature/lecture_view/LectureE2eTest.kt
The attachment tab will be removed and the content display under the lecture overview if an attachment exist (almost deprecated). Also hierarchy was missing on Lectures so the screen should be arrance by giving bigger titles and adding a overview section that wraps up, date, description and communication.
Lecture tabs removed.
Overview title added.
Lecture Unit title is bigger.
The attachemnt placed under lecture units.
Open App and go to lectures.
Verify overview title is visible lecture unit and overview are in the same size as headers, rest should be in same.
Verify tabs are removed and everything works as before.
> `Improvement`: Remove attachment tab

- core/ui/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/core/ui/common/course/CourseItem.kt
The circular indicator overflows in tablet
Fix size is used for phone and tablet layouts
Open the app 
Check a course with circular indicator
Verify the phone and tablet indicator size is looking good and tablet is not overflowing
> `Improvement`: Course circular indicator size arrangement
